apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: countkey-ingress
  annotations:
    # Ví dụ sử dụng NGINX Ingress Controller
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: countkey.your-company.com # Thay đổi domain của bạn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: countkey-service
            port:
              number: 55555
