apiVersion: v1
kind: Secret
metadata:
  name: countkey-secret
type: Opaque
stringData:
  # Sử dụng stringData để không cần base64 encode thủ công
  ELASTICSEARCH_URL: "http://10.11.32.21:30100"
  ELASTICSEARCH_DB_URL: "http://10.11.32.21:30100"
  MONGOS_HOST: "10.11.32.22"
  # Nếu có mật khẩu DB, thêm vào đây
  # DB_PASSWORD: "your-password"
