apiVersion: v1
kind: Secret
metadata:
  name: {{ include "countkey.fullname" . }}-secret
  labels:
    {{- include "countkey.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
